log:
  level: debug
  disable_sentry: true


bot:
  token: "6091782696:AAHHibjlkaeG5wgr1AhDKH1ycJ3SUQvRB3E"

listener:
  addr: :8787

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: sbt-bot
  service_port: 80
